import Nav from "@/layouts/Nav";
import "./globals.css";
import Footer from "@/layouts/Footer";
import { ModalProvider } from "@/context/modalContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ModalProvider>
          <Nav />
          {children}
          <Footer />
        </ModalProvider>
      </body>
    </html>
  );
}
