"use client"
import Nav from "@/layouts/Nav";
import "./globals.css";
import Footer from "@/layouts/Footer";
import { usePathname } from "next/navigation";
import { ModalProvider } from "@/context/modalContext";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const router = useRouter();
  const pathname = usePathname();
  const hideNavandFooter = pathname === '/auth/login' || pathname === '/auth/signup' || pathname === '/auth/forgotpassword' || pathname === '/not-found';
  return (
    <html lang="en">
  
      <body>
        <ModalProvider>
        {!hideNavandFooter && <Nav/>}
        {children}
        {!hideNavandFooter && <Footer/>}
        </ModalProvider>
      </body>
    </html>
  );
}
